### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by suredream** [ruanyf/road#3]
$ git clone https://github.com/ruanyf/road.git
$ cd road
$ loppo

/usr/local/lib/node_modules/loppo/node_modules/tarim/index.js:17
    );
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/loppo/lib/theme.js:8:20)
Juns-Air:ruan jxiong1$ 

I tried to create a project folder following the instruction, still the same problem.

**Comment by ruanyf** [comment]
你的 Node 版本太老了。
